version: "3.9"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
      dockerfile: Dockerfile
    image: litellm_local:latest
    env_file:
      - .env
    environment:
      LITELLM_MASTER_KEY: local
      DATABASE_URL: postgresql://litellm:litellm@postgres/litellm
    ports:
      - "4000:4000"
    command:
      ["--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8"]
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: litellm
      POSTGRES_DB: litellm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
